import './endangered.css';
import Card from './Card';
const mockedData = {
  "msgResponse": "Success.",
  "species": [
      {
          "name": "Osprey",
          "scientificName": "Pandion haliaetus",
          "iucnId": 22694938,
          "scope": "Majority (50-90%)",
          "severity": "Negligible declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/large.jpeg"
      },
      {
          "name": "Fiveline Cardinalfish",
          "scientificName": "Cheilodipterus quinquelineatus",
          "iucnId": 193345,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462698/square.png",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462698/thumb.png",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462698/small.png",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462698/medium.png",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462698/large.png"
      },
      {
          "name": "Dark Fishing Spider",
          "scientificName": "Dolomedes tenebrosus",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462616/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462616/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462616/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462616/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326462616/large.jpeg"
      },
      {
          "name": "Common Merganser",
          "scientificName": "Mergus merganser",
          "iucnId": 22680492,
          "scope": "Minority (<50%)",
          "severity": "Negligible declines",
          "score": "Low Impact: 4",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326461231/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326461231/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326461231/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326461231/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326461231/large.jpeg"
      },
      {
          "name": "Great Black-backed Gull",
          "scientificName": "Larus marinus",
          "iucnId": 22694324,
          "scope": "Minority (<50%)",
          "severity": "Slow, Significant Declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/large.jpeg"
      },
      {
          "name": "Cross Orbweaver",
          "scientificName": "Araneus diadematus",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463244/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463244/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463244/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463244/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463244/large.jpg"
      },
      {
          "name": "Giant Toad",
          "scientificName": "Rhinella horribilis",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://static.inaturalist.org/photos/326404461/square.jpeg",
          "thumbUr": "https://static.inaturalist.org/photos/326404461/thumb.jpeg",
          "smallUrl": "https://static.inaturalist.org/photos/326404461/small.jpeg",
          "mediumUrl": "https://static.inaturalist.org/photos/326404461/medium.jpeg",
          "largeUrl": "https://static.inaturalist.org/photos/326404461/large.jpeg"
      },
      {
          "name": "honey locust",
          "scientificName": "Gleditsia triacanthos",
          "iucnId": 62026061,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://static.inaturalist.org/photos/326461430/square.jpg",
          "thumbUr": "https://static.inaturalist.org/photos/326461430/thumb.jpg",
          "smallUrl": "https://static.inaturalist.org/photos/326461430/small.jpg",
          "mediumUrl": "https://static.inaturalist.org/photos/326461430/medium.jpg",
          "largeUrl": "https://static.inaturalist.org/photos/326461430/large.jpg"
      },
      {
          "name": "Microcaddisflies",
          "scientificName": "Hydroptilidae",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326457905/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326457905/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326457905/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326457905/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326457905/large.jpg"
      },
      {
          "name": "Micro Bee Flies",
          "scientificName": "Mythicomyiidae",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://static.inaturalist.org/photos/326428970/square.jpeg",
          "thumbUr": "https://static.inaturalist.org/photos/326428970/thumb.jpeg",
          "smallUrl": "https://static.inaturalist.org/photos/326428970/small.jpeg",
          "mediumUrl": "https://static.inaturalist.org/photos/326428970/medium.jpeg",
          "largeUrl": "https://static.inaturalist.org/photos/326428970/large.jpeg"
      },
      {
          "name": "Clematis and leatherflowers",
          "scientificName": "Clematis",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://static.inaturalist.org/photos/326418827/square.jpg",
          "thumbUr": "https://static.inaturalist.org/photos/326418827/thumb.jpg",
          "smallUrl": "https://static.inaturalist.org/photos/326418827/small.jpg",
          "mediumUrl": "https://static.inaturalist.org/photos/326418827/medium.jpg",
          "largeUrl": "https://static.inaturalist.org/photos/326418827/large.jpg"
      },
      {
          "name": "Pinion-streaked Snout",
          "scientificName": "Schrankia costaestrigalis",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326400451/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326400451/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326400451/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326400451/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326400451/large.jpeg"
      },
      {
          "name": "Coyote",
          "scientificName": "Canis latrans",
          "iucnId": 3745,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463878/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463878/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463878/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463878/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463878/large.jpeg"
      },
      {
          "name": "Mountain Lion",
          "scientificName": "Puma concolor",
          "iucnId": 18868,
          "scope": "null",
          "severity": "null",
          "score": "Low Impact: 3",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463582/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463582/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463582/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463582/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463582/large.jpeg"
      },
      {
          "name": "Mammals",
          "scientificName": "Mammalia",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326452589/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326452589/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326452589/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326452589/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326452589/large.jpeg"
      },
      {
          "name": "Oceanic Dolphins",
          "scientificName": "Delphinidae",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326446211/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326446211/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326446211/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326446211/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326446211/large.jpg"
      },
      {
          "name": "Humpback Whale",
          "scientificName": "Megaptera novaeangliae",
          "iucnId": 13006,
          "scope": "null",
          "severity": "null",
          "score": "Low Impact: 3",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326421175/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326421175/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326421175/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326421175/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326421175/large.jpg"
      },
      {
          "name": "Cetaceans",
          "scientificName": "Cetacea",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326410197/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326410197/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326410197/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326410197/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326410197/large.jpeg"
      },
      {
          "name": "Brown-banded Bamboo Shark",
          "scientificName": "Chiloscyllium punctatum",
          "iucnId": 41872,
          "scope": "Majority (50-90%)",
          "severity": "Unknown",
          "score": "Unknown",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326455470/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326455470/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326455470/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326455470/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326455470/large.jpeg"
      },
      {
          "name": "Bull Shark",
          "scientificName": "Carcharhinus leucas",
          "iucnId": 39372,
          "scope": "Minority (<50%)",
          "severity": "Slow, Significant Declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/large.jpg"
      },
      {
          "name": "Shark Eye",
          "scientificName": "Neverita duplicata",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326420851/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326420851/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326420851/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326420851/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326420851/large.jpeg"
      },
      {
          "name": "Sand Tiger Shark",
          "scientificName": "Carcharias taurus",
          "iucnId": 3854,
          "scope": "Minority (<50%)",
          "severity": "Slow, Significant Declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://static.inaturalist.org/photos/326410068/square.jpeg",
          "thumbUr": "https://static.inaturalist.org/photos/326410068/thumb.jpeg",
          "smallUrl": "https://static.inaturalist.org/photos/326410068/small.jpeg",
          "mediumUrl": "https://static.inaturalist.org/photos/326410068/medium.jpeg",
          "largeUrl": "https://static.inaturalist.org/photos/326410068/large.jpeg"
      },
      {
          "name": "Northern Pike",
          "scientificName": "Esox lucius",
          "iucnId": 135631,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326401752/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326401752/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326401752/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326401752/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326401752/large.jpg"
      },
      {
          "name": "Sierra Garter Snake",
          "scientificName": "Thamnophis couchii",
          "iucnId": 63974,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463261/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463261/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463261/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463261/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463261/large.jpeg"
      },
      {
          "name": "Helena Gum Moth",
          "scientificName": "Opodiphthera helena",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326448981/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326448981/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326448981/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326448981/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326448981/large.jpeg"
      },
      {
          "name": "Domestic Water Buffalo",
          "scientificName": "Bubalus bubalis",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326445770/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326445770/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326445770/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326445770/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326445770/large.jpg"
      },
      {
          "name": "Aquatic Milkweed",
          "scientificName": "Asclepias perennis",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326416828/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326416828/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326416828/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326416828/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326416828/large.jpeg"
      },
      {
          "name": "Meylan's Pouchwort",
          "scientificName": "Calypogeia integristipula",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326040608/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326040608/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326040608/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326040608/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326040608/large.jpeg"
      },
      {
          "name": "Littoral Whiptail-skink",
          "scientificName": "Emoia atrocostata",
          "iucnId": 195316,
          "scope": "Minority (<50%)",
          "severity": "Unknown",
          "score": "Unknown",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325972082/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/325972082/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325972082/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325972082/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325972082/large.jpeg"
      },
      {
          "name": "Twin-flowered False Bindweed",
          "scientificName": "Calystegia silvatica fraterniflora",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325547285/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/325547285/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325547285/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325547285/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325547285/large.jpeg"
      },
      {
          "name": "woodsorrels",
          "scientificName": "Oxalis",
          "iucnId": null,
          "scope": null,
          "severity": null,
          "score": null,
          "invasive": null,
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325387589/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/325387589/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325387589/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325387589/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325387589/large.jpeg"
      },
      {
          "name": "northern pin oak",
          "scientificName": "Quercus ellipsoidalis",
          "iucnId": 33896,
          "scope": "Minority (<50%)",
          "severity": "Slow, Significant Declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/large.jpg"
      }
  ],
  "endangeredSpecies": [
      {
          "name": "Osprey",
          "scientificName": "Pandion haliaetus",
          "iucnId": 22694938,
          "scope": "Majority (50-90%)",
          "severity": "Negligible declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463148/large.jpeg"
      },
      {
          "name": "Great Black-backed Gull",
          "scientificName": "Larus marinus",
          "iucnId": 22694324,
          "scope": "Minority (<50%)",
          "severity": "Slow, Significant Declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/square.jpeg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/thumb.jpeg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/small.jpeg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/medium.jpeg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326463254/large.jpeg"
      },
      {
          "name": "Bull Shark",
          "scientificName": "Carcharhinus leucas",
          "iucnId": 39372,
          "scope": "Minority (<50%)",
          "severity": "Slow, Significant Declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/326425717/large.jpg"
      },
      {
          "name": "Sand Tiger Shark",
          "scientificName": "Carcharias taurus",
          "iucnId": 3854,
          "scope": "Minority (<50%)",
          "severity": "Slow, Significant Declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://static.inaturalist.org/photos/326410068/square.jpeg",
          "thumbUr": "https://static.inaturalist.org/photos/326410068/thumb.jpeg",
          "smallUrl": "https://static.inaturalist.org/photos/326410068/small.jpeg",
          "mediumUrl": "https://static.inaturalist.org/photos/326410068/medium.jpeg",
          "largeUrl": "https://static.inaturalist.org/photos/326410068/large.jpeg"
      },
      {
          "name": "northern pin oak",
          "scientificName": "Quercus ellipsoidalis",
          "iucnId": 33896,
          "scope": "Minority (<50%)",
          "severity": "Slow, Significant Declines",
          "score": "Low Impact: 5",
          "invasive": "null",
          "squareUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/square.jpg",
          "thumbUr": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/thumb.jpg",
          "smallUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/small.jpg",
          "mediumUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/medium.jpg",
          "largeUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/325186064/large.jpg"
      }
  ]
};

function EndangeredSpecies(props) {
  const {
    speciesList,
    endangered,
    openModal,
    setSpecie,
  } = props;
  return (
    <div className="species-cont">
      <div className="title">
        <img src="./axolotl-lens.png" className="lens" width={100}/>
        {endangered ? 'Endangered species in your area' : 'Species in your area'}
      </div>
      {speciesList && (
        <div className="flex flex-row overflow-x-scroll space-x-4 mt-5 h-36 lg:h-80 card-cont">
        {speciesList.map(item => (
          <Card
            item={item}
            openModal={openModal}
            setSpecie={setSpecie}
          />
        ))}
      </div>
      )}
    </div>
  )
}

export default EndangeredSpecies;